package: yrewrite
version: '2.9.1'
author: Jan Kristinus, Gregor Harlan
supportpage: https://github.com/yakamara/redaxo_yrewrite
docspage: https://github.com/yakamara/redaxo_yrewrite/edit/main/README.md

page:
    title: YRewrite
    perm: yrewrite[forward]
    pjax: true
    subpages:
        domains: { title: 'translate:domains', perm: admin }
        alias_domains: { title: 'translate:alias_domains', perm: admin }
        forward: { title: 'translate:forward', perm: 'yrewrite[forward]' }
        setup: { title: 'translate:setup', perm: admin }
        docs: { title: 'translate:docs', icon: rex-icon fa-info-circle, itemclass: pull-right }

requires:
    php:
        version: '>=7.3'
    redaxo: '^5.13'
    packages:
        media_manager: '^2.12'
        mediapool: '^2.11'
        structure: '^2.7.0'
        yform: '>=3.2,<5.0.0-dev'
