package: yrewrite
version: '2.0'
author: Jan Kristinus, Gregor Harlan
supportpage: www.redaxo.org/de/forum/

page:
    title: YRewrite
    perm: yrewrite[forward]
    pjax: true
    subpages:
        domains: { title: 'translate:domains', perm: admin }
        alias_domains: { title: 'translate:alias_domains', perm: admin }
        forward: { title: 'translate:forward', perm: 'yrewrite[forward]' }
        setup: { title: 'translate:setup', perm: admin }

requires:
    redaxo: '^5.0'
    packages:
        structure: '^2.0'
        yform/manager: '^1.0-beta1'
