package: yrewrite
version: '2.7-dev'
author: Jan Kristinus, Gregor Harlan
supportpage: www.redaxo.org/de/forum/
docspage: https://github.com/yakamara/redaxo_yrewrite/edit/master/README.md

page:
    title: YRewrite
    perm: yrewrite[forward]
    pjax: true
    subpages:
        domains: { title: 'translate:domains', perm: admin }
        alias_domains: { title: 'translate:alias_domains', perm: admin }
        forward: { title: 'translate:forward', perm: 'yrewrite[forward]' }
        setup: { title: 'translate:setup', perm: admin }
        docs: { title: 'translate:docs', icon: rex-icon fa-info-circle, itemclass: pull-right }

requires:
    php:
        version: '^7.1'
    redaxo: '^5.7'
    packages:
        yform: '^3.2'
