name: Release

on:
    release:
        types:
            - published

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Publish to redaxo.org
                uses: FriendsOfREDAXO/installer-action@v1
                with:
                    myredaxo-username: ${{ secrets.MYREDAXO_USERNAME }}
                    myredaxo-api-key: ${{ secrets.MYREDAXO_API_KEY }}
                    description: ${{ github.event.release.body }}

